language: python
python:
  - "3.6"
dist: trusty
env:
  - BULKDIR_TEST_SET=core
matrix:
  include:
    - python: 3.6
      dist: xenial
      env: BULKDIR_TEST_SET=core
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script: pytest test.py